create table BRANCH(
         BRANCH_NAME VARCHAR2(30) NOT NULL,
         BRANCH_CITY VARCHAR2(30) NOT NULL,
         ASSETS VARCHAR2(30) NOT NULL
);

create table CUSTOMER(
         ACCOUNT_NAME VARCHAR2(30) NOT NULL,
         CUSTOMER_STREET VARCHAR2(30) NOT NULL,
         CUSTOMER_CITY VARCHAR2(30) NOT NULL
);

create table ACCOUNT(
         ACCOUNT_NUMBER VARCHAR2(30) NOT NULL,
         BRANCH_NAME VARCHAR2(30) NOT NULL,
         BALANCE NUMBER
);

create table LOAN(
         LOAN_NUMBER VARCHAR2(30) NOT NULL,
         BRANCH_NAME VARCHAR2(30) NOT NULL,
         AMOUNT NUMBER
);

create table DEPOSITOR(
         CUSTOMER_NAME VARCHAR2(30) NOT NULL,
         ACCOUNT_NUMBER VARCHAR2(30) NOT NULL
);

create table borrower(
         CUSTOMER_NAME VARCHAR2(30) NOT NULL,
         LOAN_NUMBER VARCHAR2(30) NOT NULL
);

